# Generated by Django 4.0 on 2022-07-12 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='users.department_mode'),
        ),
    ]
