# Generated by Django 4.0 on 2022-07-21 01:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department_mode',
            name='desc_gid',
            field=models.IntegerField(blank=True, choices=[(1001, '运维部'), (1002, '测试部'), (1003, '研发部')], null=True, verbose_name='部门组'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间'),
        ),
    ]
