# Generated by Django 4.0 on 2022-06-27 03:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('salt_id', models.CharField(max_length=16, verbose_name='saltid')),
                ('master_ip', models.CharField(max_length=20, verbose_name='公网IP')),
                ('private_ip', models.CharField(max_length=20, verbose_name='内网IP')),
                ('system', models.CharField(default='', max_length=50, verbose_name='系统版本')),
                ('cpu_core', models.IntegerField(default='8', verbose_name='系统核数')),
                ('memory', models.IntegerField(default='64', verbose_name='内存')),
                ('max_port', models.IntegerField(verbose_name='最大使用端口')),
                ('current_server', models.CharField(max_length=100, verbose_name='现有游服')),
                ('status', models.IntegerField(verbose_name='状态')),
            ],
            options={
                'verbose_name': '服务器列表',
                'verbose_name_plural': '服务器列表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('server_id', models.IntegerField(verbose_name='游服id')),
                ('special_server', models.CharField(max_length=10, verbose_name='专服')),
                ('salt_id', models.CharField(max_length=16, verbose_name='saltid')),
                ('status', models.IntegerField(blank=True, null=True, verbose_name='状态')),
                ('version', models.CharField(blank=True, max_length=20, null=True, verbose_name='后端版本')),
                ('server_host', models.CharField(blank=True, max_length=20, null=True, verbose_name='公网IP')),
                ('private_host', models.CharField(blank=True, max_length=20, null=True, verbose_name='内网IP')),
                ('ws_server_port', models.IntegerField(blank=True, null=True, verbose_name='ws端口号')),
                ('web_port', models.IntegerField(blank=True, null=True, verbose_name='web端口号')),
                ('fep_client_port', models.IntegerField(blank=True, null=True, verbose_name='fep_client端口号')),
                ('fep_server_port', models.IntegerField(blank=True, null=True, verbose_name='fep_server端口号')),
                ('dp_server_port', models.IntegerField(blank=True, null=True, verbose_name='dp端口号')),
                ('nginx_port', models.IntegerField(blank=True, null=True, verbose_name='nginx端口号')),
                ('clb', models.CharField(blank=True, max_length=20, null=True, verbose_name='负载均衡名')),
                ('born_time', models.CharField(default=0, max_length=20, verbose_name='开服时间')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创服时间')),
            ],
            options={
                'verbose_name': '服务器列表',
                'verbose_name_plural': '服务器列表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=10, verbose_name='专服名')),
                ('salt_range', models.CharField(max_length=50, verbose_name='salt范围')),
                ('id_range', models.CharField(max_length=50, verbose_name='游服id范围')),
                ('begin', models.IntegerField(verbose_name='首服id')),
                ('front_ver', models.IntegerField(verbose_name='前端版本号')),
                ('backend_ver', models.CharField(max_length=30, verbose_name='后端版本号')),
                ('clb', models.CharField(max_length=15, verbose_name='负载均衡名')),
                ('clb_num', models.IntegerField(verbose_name='负载均衡数')),
            ],
            options={
                'verbose_name': '专服列表',
                'verbose_name_plural': '专服列表',
                'ordering': ['id'],
            },
        ),
    ]
