# Generated by Django 4.0 on 2022-04-14 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='member',
        ),
    ]
