# Generated by Django 4.0 on 2022-07-21 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='auth_group',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=100, unique=True, verbose_name='组名')),
                ('enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('explanation', models.TextField(verbose_name='角色描述')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('group_user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '角色管理',
                'verbose_name_plural': '角色管理',
            },
        ),
        migrations.CreateModel(
            name='user_auth_cmdb',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('select_host', models.BooleanField(default=False, verbose_name='查看资产')),
                ('apps', models.BooleanField(default=False, verbose_name='查看项目')),
                ('hls', models.BooleanField(default=False, verbose_name='唤灵师')),
                ('add_user', models.BooleanField(default=False, verbose_name='添加用户')),
                ('edit_user', models.BooleanField(default=False, verbose_name='修改用户')),
                ('edit_pass', models.BooleanField(default=False, verbose_name='修改密码')),
                ('delete_user', models.BooleanField(default=False, verbose_name='删除用户')),
                ('add_department', models.BooleanField(default=False, verbose_name='部门管理')),
                ('auth_log', models.BooleanField(default=False, verbose_name='salt执行记录')),
                ('group_name', models.ForeignKey(help_text='添加角色组权限', on_delete=django.db.models.deletion.CASCADE, to='cmdb_auth.auth_group', verbose_name='所属角色')),
            ],
            options={
                'verbose_name': '权限管理',
                'verbose_name_plural': '权限管理',
            },
        ),
    ]
