# Generated by Django 4.0 on 2022-07-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb_auth', '0002_rename_enable_auth_group_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth_group',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='角色描述'),
        ),
    ]
