# Generated by Django 4.0 on 2022-03-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=5)),
                ('number', models.DecimalField(decimal_places=0, max_digits=11)),
                ('address', models.CharField(max_length=50)),
                ('status', models.IntegerField(max_length=1)),
            ],
            options={
                'verbose_name': '会员',
            },
        ),
    ]
