# Generated by Django 4.0 on 2022-07-21 01:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ssh_audit',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20, verbose_name='操作用户')),
                ('bash_shell', models.TextField(verbose_name='命令')),
                ('audit_data_time', models.DateTimeField(verbose_name='操作时间')),
                ('server_ip', models.GenericIPAddressField(verbose_name='u服务器ip')),
            ],
            options={
                'verbose_name': '审计',
                'verbose_name_plural': '审计',
            },
        ),
    ]
