# Generated by Django 4.0 on 2022-06-22 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('group_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='群组ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='群组名')),
            ],
            options={
                'verbose_name': '主机群',
                'verbose_name_plural': '主机群',
                'ordering': ['group_id'],
            },
        ),
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('host_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='主机ID')),
                ('host_name', models.CharField(max_length=256, verbose_name='主机名')),
                ('error', models.CharField(default='', max_length=256, verbose_name='error')),
                ('available', models.CharField(choices=[('0', '未知'), ('1', '可用'), ('2', '失效')], default=0, max_length=1, verbose_name='agent可用性')),
                ('snmp_available', models.CharField(choices=[('0', '未知'), ('1', '可用'), ('2', '失效')], default=0, max_length=1, verbose_name='snmp可用性')),
                ('ipmi_available', models.CharField(choices=[('0', '未知'), ('1', '可用'), ('2', '失效')], default=0, max_length=1, verbose_name='ipmi可用性')),
                ('jmx_available', models.CharField(choices=[('0', '未知'), ('1', '可用'), ('2', '失效')], default=0, max_length=1, verbose_name='jmx可用性')),
                ('groups', models.ManyToManyField(related_name='hosts', to='zabbix.Groups')),
            ],
        ),
    ]
